// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ErrorCode } from "./ErrorCode";
import type { RecoveryAction } from "./RecoveryAction";

export type AppError = { code: ErrorCode, message: string, retryable: boolean, recoveryAction: RecoveryAction | null, diagnosticId: string, };
