// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BindingView } from "./BindingView";

export type BindingsRepairResponse = { binding: BindingView, };
