// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BindingTargetView = { skillId: string, path: string, readerAgentIds: Array<string>, status: string, };
