// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BindingsCreateRequest = { skillIds: Array<string>, scope: string, projectRootId: string | null, agentIds: Array<string>, };
