// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LibraryState } from "./LibraryState";

export type CompleteOnboardingResponse = { libraryState: LibraryState, libraryId: string, currentRevision: string, };
