// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CandidateDuplicate } from "./CandidateDuplicate";
import type { ValidationSummary } from "./ValidationSummary";

export type DiscoveryCandidate = { candidateId: string, locationId: string, displayPath: string, slug: string, name: string | null, description: string | null, readerAgentIds: Array<string>, validation: ValidationSummary, duplicate: CandidateDuplicate, fileCount: number, totalBytes: string, linked: boolean, warnings: Array<string>, };
