// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DiscoveryProgress = { rootsTotal: number, rootsDone: number, entriesSeen: number, candidatesFound: number, currentPath: string | null, };
