// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiscoveryCandidate } from "./DiscoveryCandidate";
import type { DiscoveryProgress } from "./DiscoveryProgress";
import type { ScanPhase } from "./ScanPhase";

export type DiscoveryResultsResponse = { scanId: string, phase: ScanPhase, registryVersion: number, progress: DiscoveryProgress, limitsReached: boolean, candidates: Array<DiscoveryCandidate>, totalCandidates: number, hiddenDuplicates: number, offset: number, limit: number, failure: string | null, };
