// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LibrarySkillPreviewResponse = { skillId: string, lastEditedAt: number | null, files: Array<string>, path: string, content: string | null, unavailableReason: string | null, };
