// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SkillSource } from "./SkillSource";
import type { ValidationSummary } from "./ValidationSummary";

export type LibrarySkill = { skillId: string, slug: string, displayName: string | null, description: string | null, validation: ValidationSummary, fileCount: number, totalBytes: string, sources: Array<SkillSource>, };
