// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LibrarySkill } from "./LibrarySkill";

export type LibraryListResponse = { libraryRevision: string | null, hasUncommittedChanges: boolean, skills: Array<LibrarySkill>, };
