// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LibraryResolveConflictResponse = { slug: string, keptSkillId: string, removedSkillIds: Array<string>, payloadDirectory: string, libraryRevision: string | null, hasUncommittedChanges: boolean, };
