// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type OrganizationDeletePreviewResponse = { childFolders: number, affectedSkills: number, organizationRevision: string, };
