// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OrganizationChange } from "./OrganizationChange";

export type OrganizationChangeRequest = { change: OrganizationChange, expectedRevision: string | null, };
