// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RootView = { rootId: string, displayPath: string, resolvedPath: string, label: string, enabled: boolean, };
