// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RootGrantView } from "./RootGrantView";

export type RootsPickResponse = { grant: RootGrantView | null, };
