// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ValidationMessage } from "./ValidationMessage";
import type { ValidationStatus } from "./ValidationStatus";

export type ValidationSummary = { status: ValidationStatus, messages: Array<ValidationMessage>, };
