// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ValidationCode } from "./ValidationCode";

export type ValidationMessage = { code: ValidationCode, message: string, };
