// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ValidationCode = "missingSkillFile" | "invalidFrontmatter" | "unsupportedYaml" | "invalidUtf8" | "nameMissing" | "nameMismatch" | "nameTooLong" | "nameHyphenRule" | "descriptionMissing" | "descriptionTooLong" | "unsafeEntryPath" | "reservedEntryName" | "caseCollision" | "unsupportedEntryType" | "externalSymlink" | "linkCycle" | "vcsMetadataExcluded" | "pluginManifest" | "payloadLimitExceeded" | "fileLimitExceeded" | "indexNotBuilt";
