/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as ShellDiscoveryRouteImport } from './routes/_shell.discovery'
import { Route as ShellGitRouteImport } from './routes/_shell.git'
import { Route as ShellLibraryRouteImport } from './routes/_shell.library'
import { Route as ShellSettingsRouteImport } from './routes/_shell.settings'
import { Route as ShellLibraryFolderIdRouteImport } from './routes/_shell.library_.$folderId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellDiscoveryRoute = ShellDiscoveryRouteImport.update({
  id: '/discovery',
  path: '/discovery',
  getParentRoute: () => ShellRoute,
} as any)
const ShellGitRoute = ShellGitRouteImport.update({
  id: '/git',
  path: '/git',
  getParentRoute: () => ShellRoute,
} as any)
const ShellLibraryRoute = ShellLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => ShellRoute,
} as any)
const ShellSettingsRoute = ShellSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ShellRoute,
} as any)
const ShellLibraryFolderIdRoute = ShellLibraryFolderIdRouteImport.update({
  id: '/library_/$folderId',
  path: '/library/$folderId',
  getParentRoute: () => ShellRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/discovery': typeof ShellDiscoveryRoute
  '/git': typeof ShellGitRoute
  '/library': typeof ShellLibraryRoute
  '/settings': typeof ShellSettingsRoute
  '/library/$folderId': typeof ShellLibraryFolderIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/discovery': typeof ShellDiscoveryRoute
  '/git': typeof ShellGitRoute
  '/library': typeof ShellLibraryRoute
  '/settings': typeof ShellSettingsRoute
  '/library/$folderId': typeof ShellLibraryFolderIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_shell': typeof ShellRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/_shell/discovery': typeof ShellDiscoveryRoute
  '/_shell/git': typeof ShellGitRoute
  '/_shell/library': typeof ShellLibraryRoute
  '/_shell/settings': typeof ShellSettingsRoute
  '/_shell/library_/$folderId': typeof ShellLibraryFolderIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/onboarding'
    | '/discovery'
    | '/git'
    | '/library'
    | '/settings'
    | '/library/$folderId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/onboarding'
    | '/discovery'
    | '/git'
    | '/library'
    | '/settings'
    | '/library/$folderId'
  id:
    | '__root__'
    | '/'
    | '/_shell'
    | '/onboarding'
    | '/_shell/discovery'
    | '/_shell/git'
    | '/_shell/library'
    | '/_shell/settings'
    | '/_shell/library_/$folderId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ShellRoute: typeof ShellRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/discovery': {
      id: '/_shell/discovery'
      path: '/discovery'
      fullPath: '/discovery'
      preLoaderRoute: typeof ShellDiscoveryRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/git': {
      id: '/_shell/git'
      path: '/git'
      fullPath: '/git'
      preLoaderRoute: typeof ShellGitRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/library': {
      id: '/_shell/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof ShellLibraryRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/settings': {
      id: '/_shell/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ShellSettingsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/library_/$folderId': {
      id: '/_shell/library_/$folderId'
      path: '/library/$folderId'
      fullPath: '/library/$folderId'
      preLoaderRoute: typeof ShellLibraryFolderIdRouteImport
      parentRoute: typeof ShellRoute
    }
  }
}

interface ShellRouteChildren {
  ShellDiscoveryRoute: typeof ShellDiscoveryRoute
  ShellGitRoute: typeof ShellGitRoute
  ShellLibraryRoute: typeof ShellLibraryRoute
  ShellSettingsRoute: typeof ShellSettingsRoute
  ShellLibraryFolderIdRoute: typeof ShellLibraryFolderIdRoute
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellDiscoveryRoute: ShellDiscoveryRoute,
  ShellGitRoute: ShellGitRoute,
  ShellLibraryRoute: ShellLibraryRoute,
  ShellSettingsRoute: ShellSettingsRoute,
  ShellLibraryFolderIdRoute: ShellLibraryFolderIdRoute,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ShellRoute: ShellRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
